# Generated by Django 3.1 on 2020-12-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='personality_link',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
