# Generated by Django 3.1 on 2020-12-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_personality_personality_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personality',
            name='personality_points',
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_points1',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_points2',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_points3',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_points4',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_points5',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_points6',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_points7',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_points8',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
