# Generated by Django 3.1 on 2020-12-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20201225_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='personality_letter',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='personality',
            name='personality_llink',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
