# Generated by Django 3.1 on 2020-12-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_auto_20201229_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='personality_llink',
        ),
    ]
